### ISSUE TITLE
It won't work when I add it to my site

### ISSUE THREAD

**Issue by TFM110** [frontendcharm/Mini-Projects#1]
I have been trying to add the [Submit Button Animation](https://codepen.io/frontendcharm/pen/BaqOpor) to my site, but for some reason, its not working. Proably cause I am not that good of a coder that I am doing something wrong but I'm not sure. Here is my code. You help would be greatly appreciated

https://github.com/TFM110/TFM110.github.io/blob/05d6319a10273cd780feac6f2af22ee57aec3707/index.html#L590
```html
<div class="col-lg-8 mt-5 mt-lg-0">
            <form class="email-form" id="contact-form">
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" id="name" name="name" class="form-control" placeholder="Please enter your Name *" required data-error="Name is required."/>
                </div>
                <div class="col-md-6 form-group mt-3 mt-md-0">
                  <input type="text" id="email" name="email" class="form-control" placeholder="Please enter your Email *" required data-error="Email is required."/>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject *" required/>
              </div>
              <div class="form-group mt-3">
                <textarea id="message" name="message" rows="5" class="form-control" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading" style="display: none">Loading</div>
                <div class="error-message" style="display: none"></div>
                <div class="sent-message" style="display: none">Your message has been sent. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Send Message</button></div>
            </form>
          </div>
``` 

https://github.com/TFM110/TFM110.github.io/blob/05d6319a10273cd780feac6f2af22ee57aec3707/assets/css/style.css#L912
```css
.contact .email-form {
  width: 100%;
  background: #fff;
}

.contact .email-form .form-group {
  padding-bottom: 8px;
}

.contact .email-form .error-message {
  display: none;
  color: #fff;
  background: #ed3c0d;
  text-align: left;
  padding: 15px;
  font-weight: 600;
}

.contact .email-form .error-message br+br {
  margin-top: 25px;
}

.contact .email-form .sent-message {
  display: none;
  color: #fff;
  background: #18d26e;
  text-align: center;
  padding: 15px;
  font-weight: 600;
}

.contact .email-form .loading {
  display: none;
  background: #fff;
  text-align: center;
  padding: 15px;
}

.contact .email-form .loading:before {
  content: "";
  display: inline-block;
  border-radius: 50%;
  width: 24px;
  height: 24px;
  margin: 0 10px -6px 0;
  border: 3px solid #18d26e;
  border-top-color: #eee;
  animation: animate-loading 1s linear infinite;
}

.contact .email-form input,
.contact .email-form textarea {
  border-radius: 4px;
  box-shadow: none;
  font-size: 14px;
}

.contact .email-form input {
  height: 44px;
}

.contact .email-form textarea {
  padding: 10px 12px;
}

.contact .email-form button[type=submit] {
  background: #0563bb;
  border: 0;
  padding: 10px 35px;
  color: #fff;
  transition: 0.4s;
  border-radius: 50px;
}

.contact .email-form button[type=submit]:hover {
  background: #0678e3;
}

@keyframes animate-loading {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
``` 

https://github.com/TFM110/TFM110.github.io/blob/05d6319a10273cd780feac6f2af22ee57aec3707/assets/js/features.js#L92
```javascript
const url = 'https://script.google.com/macros/s/AKfycbyAQDr_PwlWDI_6sGqiTNkdc0T4BX8AWeLmCOtf3Iv-f9WlYh4m2XodInEuF42yutvcBQ/exec';
const contactForm = document.getElementById('contact-form');
const loadingMessage = document.querySelector('.loading');
const errorMessage = document.querySelector('.error-message');
const sentMessage = document.querySelector('.sent-message');
  
contactForm.addEventListener('submit', function (event) {
    event.preventDefault();
  
    loadingMessage.style.display = 'block'; // Show loading message
  
    const formData = new FormData(this);
    const data = Object.fromEntries(formData);
  
    fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'text/plain;charset=utf-8',
        },
        body: JSON.stringify(data),
    })
    .then((res) => res.json())
    .then((data) => {
        console.log('Successful', data);
        this.reset();
        loadingMessage.style.display = 'none'; // Hide loading message
        sentMessage.style.display = 'block'; // Show success message
        setTimeout(function () {
            sentMessage.style.display = 'none'; // Hide success message after a few seconds
        }, 5000);
    })
    .catch((err) => {
        console.log('err', err);
        loadingMessage.style.display = 'none'; // Hide loading message
        errorMessage.style.display = 'block'; // Show error message
    });
});
```
